//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Films
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int GenreID { get; set; }
        public string YearOfProduction { get; set; }
        public string Country { get; set; }
        public string DirectedBy { get; set; }
    
        public virtual Genre Genre { get; set; }
    }
}
